### ISSUE TITLE
Update migration doc

### ISSUE THREAD

**Issue by sacOO7** [ably/laravel-broadcaster#13]
- Update migration doc for handling `ably specific descriptive errors`.
- Debug `here` method call on `presenceChannel`. Currently standard is implemented to detect every member change. Need to check how it works with `pusher-client` and `pusher-broadcaster` pointing to `pusher-server` via `pusher-specific-keys`

**Comment by qsdstefan** [comment]
We found that the `here` method gets called only once (upon joining a channel) with Pusher.js and Ably Pusher Adapter, but with Ably Laravel Broadcaster it's called on every presence change, as per comment in [presence-channel.ts](https://github.com/ably-forks/laravel-echo/blob/dc323eca49f5e67446479263c55677c3016cbf64/src/channel/presence-channel.ts#L10)

**Comment by qsdstefan** [comment]
In addition, the `members` array returned by Pusher differs from the one we're returning.

Pusher:
```json
[
    {
        "id": 1,
        "name": "John Doe",
        "capability": [
            "subscribe",
            "history",
            "channel-metadata",
            "presence",
            "publish"
        ]
    }
]
````

Ably:
```json
[
    {
        "clientId": "1",
        "action": 1,
        "data": {
            "id": 1,
            "name": "John Doe"
        },
        "encoding": null
    }
]
```

@sacOO7 has set out to make these objects consistent
