### ISSUE TITLE
Need Laravel 10 support

### ISSUE THREAD

**Issue by takielias** [ably/laravel-broadcaster#29]
Do you have a plan to release Laravel 10 support?

**Comment by sacOO7** [comment]
Yes, we will be releasing support for laravel 10 on Monday. I will try to talk to one of our devs, in case we can get it done sooner :👍. You can see the latest release PR 
https://github.com/ably/laravel-broadcaster/pull/27

**Comment by sacOO7** [comment]
Meanwhile, you can install package as a GitHub package , to use it in laravel 10 https://stackoverflow.com/questions/38323965/installing-github-package-into-laravel-project-using-composer

**Comment by sacOO7** [comment]
Hi @takielias, we have made the official release. You should now be able to use the package using `composer install ` .

Thanks
