### ISSUE TITLE
Update Ably Laravel Broadcaster to support Laravel 11

### ISSUE THREAD

**Issue by zoranlorkovic** [ably/laravel-broadcaster#42]
Dependencies needs to be upgraded (PHP 8.2, illuminate/support 11 etc).

Not sure about the code/readme....

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4689) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Okay seems laravel 11 is released already => https://laravel-news.com/laravel-11. We will update dependencies for the same 👍

**Comment by zoranlorkovic** [comment]
yes. Basically I think only dependencies needs to be updated to php 8.2, illuminate/support 11 etc.

**Comment by sacOO7** [comment]
Hi @zoranlorkovic we have added support for laravel 11 as a part of new release. Please do check 👍

**Comment by zoranlorkovic** [comment]
Hi @sacOO7,

Great, thank you. That was fast! I'm still waiting for few other packages to update and when they do, I'll try to update the whole project to Laravel 11.
