### ISSUE TITLE
Using ->toOthers() results in a "Ably error: Malformed message; invalid connectionKey" Same as issue 38

### ISSUE THREAD

**Issue by graphem** [ably/laravel-broadcaster#48]
Hi!

Seems I am getting this as well when using the method in Laravel. I have all the latest packages and Laravel 11 latest.

`broadcast(new ChatMessageCreated($message))->toOthers();`

Result in:

[2024-09-15 01:38:06] local.ERROR: Ably error: Malformed message; invalid connectionKey {"userId":1,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Ably error: Malformed message; invalid connectionKey at /vendor/ably/laravel-broadcaster/src/AblyBroadcaster.php:187)

I check the X-Socket-Id, it is there. And the socket is in the payload sent to the Rest api

I am really not sure what causes this. I do see that have a couple of websocket initiating, I did connect to different channels as I have a channel fro chat, for announcement and for some other events.

So not sure why the socket id a invalid connectionkey.

I check both on the front end and in the AblyBroadcaster.php and the key are exactly the same.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4977) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Hi @graphem thanks for raising the issue. Can you confirm you are using laravel-echo at client side? It will be great if you can create a dummy repo that can help us reproduce the issue. Then we can try to fix it ASAP.

**Comment by graphem** [comment]
Yes I am using Echo. I will see what I can do for the dummy repo. Thanks!

**Comment by sacOO7** [comment]
> Yes I am using Echo. I will see what I can do for the dummy repo. Thanks!

Thanks, that would be super useful 👍

**Comment by graphem** [comment]
@sacOO7 Here is the repo:
https://github.com/graphem/build-a-realtime-chat-with-laravel-vue-and-pinia

You will need to run the migration and add a room in the DB, then visit the /rooms/{slug}. Then you will see the 500 happening on trying to publish a message.

Thanks!!

**Comment by sacOO7** [comment]
@graphem thanks for creating the repo. We will try to reproduce from our side and post updates here

**Comment by graphem** [comment]
@sacOO7 Were you able to reproduce?

**Comment by sacOO7** [comment]
Hi @graphem I was able to reproduce the issue. Although, I had to manually edit the db for rooms. Btw, does this code work properly for reverb?

**Comment by sacOO7** [comment]
Seems I have found out the issue. This also needs sending `clientId` as per https://ably.com/docs/channels#publish-on-behalf. Currently, we are only sending `connectionKey`. This will work when user is not logged in. But for logged in user, we need to send `clientId` as well. This will require updating both `laravel-broadcaster` and `laravel-echo` packages. We should be able to update the same in next few days 👍

**Comment by graphem** [comment]
And yes the project works fine with Reverb.

**Comment by sacOO7** [comment]
Hi @graphem issue is fixed and released in latest versions of laravel-broadcaster and laravel-echo ( fix on the master branch, will be published soon ).

**Comment by sacOO7** [comment]
Btw, do star both repos if you feel like it : )

**Comment by graphem** [comment]
Amazing! Will test it out soon
